from flask import Blueprint, jsonify, request, send_from_directory, current_app
from flask_login import login_required, current_user
from app.models.report import Report as ReportModel
from app.models.alert import Alert
from app.services.report_generator import ReportGenerator
from app.services.logger import log_event
from app import db
import os
from datetime import datetime

report_bp = Blueprint('api_report', __name__)

@report_bp.route('/list')
@login_required
def list_reports():
    reports = ReportModel.query.order_by(ReportModel.timestamp.desc()).all()
    return jsonify([r.to_dict() for r in reports])

@report_bp.route('/generate', methods=['POST'])
@login_required
def generate_report():
    data = request.get_json(silent=True) or {}
    report_type = data.get('report_type', 'PDF').upper() # PDF or CSV
    
    if report_type not in ['PDF', 'CSV']:
        return jsonify({'success': False, 'error': 'Invalid report type. Choose PDF or CSV.'}), 400
        
    try:
        # Create output directory
        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        reports_dir = os.path.join(base_dir, 'instance', 'reports')
        os.makedirs(reports_dir, exist_ok=True)
        
        timestamp_str = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
        filename = f"security_report_{timestamp_str}.{report_type.lower()}"
        filepath = os.path.join(reports_dir, filename)
        
        success = False
        if report_type == 'CSV':
            alerts = Alert.query.filter(Alert.status != 'Deleted').all()
            success = ReportGenerator.generate_csv_report(filepath, alerts)
        else: # PDF
            success = ReportGenerator.generate_pdf_report(filepath, current_user.username)
            
        if success:
            new_report = ReportModel(
                timestamp=datetime.utcnow(),
                name=filename,
                report_type=report_type,
                filepath=filepath,
                generated_by=current_user.username
            )
            db.session.add(new_report)
            db.session.commit()
            
            log_event('System', 'INFO', f"{report_type} report '{filename}' generated by user '{current_user.username}'.")
            return jsonify({'success': True, 'report': new_report.to_dict()})
        else:
            return jsonify({'success': False, 'error': 'Failed to compile file.'}), 500
            
    except Exception as e:
        db.session.rollback()
        log_event('System', 'ERROR', f"Error generating report: {str(e)}")
        return jsonify({'success': False, 'error': str(e)}), 500

@report_bp.route('/download/<int:report_id>')
@login_required
def download_report(report_id):
    report_obj = ReportModel.query.get_or_404(report_id)
    try:
        directory = os.path.dirname(report_obj.filepath)
        filename = os.path.basename(report_obj.filepath)
        return send_from_directory(directory, filename, as_attachment=True)
    except Exception as e:
        return jsonify({'success': False, 'error': f"File not found: {str(e)}"}), 404
